post http://localhost:3001/flight/addFlight
Content-Type: application/json

{
    "Altitude":1450,
    "His":100,
    "ADI":29
}

###

post http://localhost:3001/flight/searchFlightByHis
Content-Type: application/json

{
    "His":200
}

###

post http://localhost:3001/flight/searchFlightByADI
Content-Type: application/json

{
    "ADI":5
}

###

post http://localhost:3001/flight/searchFlightByAltitude
Content-Type: application/json

{
    "Altitude":200
}

###

post http://localhost:3001/flight/getAllFlights
Content-Type: application/json
